export enum EDatagridTableStateChangeEvents {
    CHANGE_DATA = 'CHANGE_DATA',
    CHANGE_PAGE = 'CHANGE_PAGE',
    CHANGE_SORT = 'CHANGE_SORT',
    CHANGE_COLUMN_ORDER = 'CHANGE_COLUMN_ORDER',
    CHANGE_COLUMN_VISIBILITY = 'CHANGE_COLUMN_VISIBILITY',
    CHANGE_COLUMN_FILTER = 'CHANGE_COLUMN_FILTER',
    CHANGE_COLUMN_FILTER_RESET = 'CHANGE_COLUMN_FILTER_RESET',
    CHANGE_COLUMN_FILTER_UPDATE = 'CHANGE_COLUMN_FILTER_UPDATE',
    CHANGE_SELECTION_ROW = 'CHANGE_SELECTION_ROW',
}